[build]
  base = "hadrians-wall-smart-map"
  command = "npm install && npm run build"
  publish = ".svelte-kit/output"

[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_FLAGS = "--include=optional"
