[build]
  base = "hadrians-wall-smart-map"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_FLAGS = "--include=optional"
